.\" -*- mode: troff; coding: utf-8 -*-
.TH "GMENU2 " "1" "2024-02-02 "
.SH
gmenu2
.LP
Alternative desktop menu implementation using gtkmenuplus
.SS
Compatibility
.LP
Gmenu2 loosely follows the specification for XDG menu applications.
It is developed for Fatdog64 Linux, and it could be lacking for other
distributions.
.SS
Target User
.LP
You remaster Fatdog64 and want a stand-alone application menu that works
without a window manager or a desktop panel.
.SS
Installing
.LP
This script can be installed from a command line shell prompt.
It should be installed to «\fC/\fR» for system-wide availability.
.PP
It can be started from a shell prompt.  The installer also adds a \(dqGmenu2\(dq
entry in section \(dqDesktop\(dq of the system application menu.
.PP
First, install all dependencies, see \fBDependencies\fR.
Then, optionally install extensions, see \fBExtensions\fR.
.PP
Then download the latest archive \fBattachment\fR from the release page\fB:1\fR.
Unpack the archive into a folder of your choice.
.PP
From that folder run the following command: «\fCinstall/bin/install.sh\fR».
This will start an interactive installer, which includes a Help screen.
.PP
Assuming a successful installation with default settings, enter command
«\fCgmenu2\fR» in a shell prompt to display the gmenu2 menu.
Probably several non-fatal error messages will be printed to the terminal
but as long as the menu is displayed all is good.
.PP
\fBImportant\fR --- After having completed the installation you \fBmust\fR save file
«\fCinstall.log\fR», which is located in folder «\fCinstall/\fR», if you want to be able to
uninstall gmenu2 in the future.  Indeed, it is recommended to save the
whole folder «\fCinstall/\fR», which holds the uninstall program and the log file.
.PP
.SS
Dependencies
.LP
Install «\fCgtkmenuplus\fR»\fB:2\fR».
.IP "\(bu" 3
Since version 800, Fatdog64 includes gtkmenuplus; no need to install it again.
.LP
.SS
Extensions
.LP
If «\fCquicklaunch\fR» is installed, it can share recently selected menu entries with
gmenu2.
.IP "\(bu" 3
Optional: install «\fCquicklaunch\fR»\fB:5\fR».
See also section \fBConfiguration\fR.
.LP
If «\fCgmenu2-fdcp\fR» is installed, gmenu2 will display menu entries for the
Fatdog64 Control Panel. This extension is only needed for Fatdog64 <= 802.
.IP "\(bu" 3
Optional: install «\fCgmenu2-fdcp\fR»\fB:6\fR».
.SS
Uninstalling
.LP
From the folder where you unpacked the downloaded archive run the following
command: «\fCinstall/bin/uninstall.sh\fR».
This will start an interactive uninstaller, which includes a Help screen.
.PP
The uninstaller will not remove the user's configuration files:
«\fC\(ti/.gmenu2rc\fR» and «\fC\(ti/.gmenu2.log\fR».
.SS
Submenus
.LP
In addition to providing the system application menu, gmenu2 provides some
submenus of its own:
.RS
.PP
Control panel
.RE
.PP
See \fBExtensions\fR.
.RS
.PP
Recent
.PP
Tools
.PP
Uncategorized
.RE
.PP
See \fBConfiguration\fR.
.RS
.PP
Wine
.RE
.PP
If the Wine emulator is installed, and it is configured to add Wine
applications to the system menu, this submenu will show such applications.
.PP
.SS
Configuration
.SS
Preferences file
.LP
Gmenu2 self-configures on the first run; you do not need to do anything.
You can change some menu preferences directly from
the gmenu2 menu, and also by editing file «\fC\(ti/.gmenu2rc\fR», which gmenu2 creates
if the file does not exist.  Default preferences:
.RS
.PP
«\fCIGNORENODISPLAY=\(dq0\(dq\fR»
.RE
.PP
If this setting is enabled (\(dq1\(dq) gmenu2 will not hide the application menu
entries that the default system application menu always hides.
You can toggle this setting by selecting \(dqGmenu2 > Show concealed applications\(dq
in gmenu2.
.RS
.PP
«\fCINLINE=\(dq1\(dq\fR»
.RE
.PP
If this setting is disabled (\(dq0\(dq) gmenu2 will not group applications by
categories but instead the menu will be a very long, flat list of entries. This
is probably not what you want.  This setting is not exposed in the menu. If you
experiment and change it, and then set it back, you will also need to remove
the menu cache directory, «\fC/tmp/gmenu_$USER\fR», where «\fC$USER\fR» is your login name.
.RS
.PP
«\fCREFRESH_CACHE=\(dq0\(dq\fR»
.RE
.PP
If this setting is enabled (\(dq1\(dq) gmenu2 will rebuild the menu cache each time
it is invoked. Building the cache delays showing the menu.
It this setting is disabled (\(dq0\(dq) gmenu2 will build the cache automatically
only if it does not already exist.  This displays the menu faster (after the
first menu invocation) but gmenu2 will not display entries for newly installed
applications unless you tell it to update the cache.
.PP
You can force cache updates by selecting \(dqGmenu2 > Refresh cache\(dq in gmenu2.
Forced updates will keep going until disabled with
\(dqGmenu2 > Stop refreshing the cache\(dq.
.RS
.PP
«\fCSUBMENU_UNCATEGORIZED_APPS=\(dq0\(dq\fR»
.RE
.PP
Application packagers may choose not to assign an application to any known
application category. In this case the application is not listed in the default
system application menu. By enabling this setting (\(dq1\(dq) such uncategorized
applications will be listed in the \(dqUncategorized\(dq submenu.
.RS
.PP
«\fCSUBMENU_ACTIVATIONS=\(dq1\(dq\fR»
.RE
.PP
If this setting is enabled (\(dq1\(dq), all menu entry activations will be logged
to the file specified by user preference «\fCLOGFILE_ACTIVATIONS\fR», and shown
in the \(dqRecent\(dq submenu.
.PP
If «\fCquicklaunch\fR»[:5] is installed it will share its own Recent submenu items
with gmenu2 via the log file. This way whatever entry is activated in one menu
will also be seen in the other menu's Recent submenu.
.RS
.PP
«\fCLOGFILE_ACTIVATIONS=\(dq/root/.gmenu2.log\(dq\fR»
.RE
.PP
This file logs all activations (if enabled) in a format suitable for sharing
with «\fCquicklaunch\fR»[:5].
.RS
.PP
«\fCMNEMONIC=\(dq1\(dq\fR»
.RE
.PP
If this setting is disabled (\(dq0\(dq) gmenu2 will not add keyboard accelerators of
its own.  The keyboard key that corresponds to a label's underlined character,
if one exists, can be pressed to jump to that label, which is therefore said
\(dqaccelerated\(dq.  If «\fCMNEMONIC\fR» is «\fC\(dq1\(dq\fR» gmenu2 will set the first character of
each \(dqunaccelerated\(dq label as its accelerator.
.RS
.PP
«\fCICONSIZE=\(dq24\(dq\fR»
.RE
.PP
The size of menu item icons in pixels.
.SS
Assigning a global hotkey (optional)
.LP
The following instructions apply to sven\fB:3\fR --- the multimedia
keyboard manager in Fatdog64 Linux\fB:4\fR.
They assume that key Windows+s isn't already assigned as a hotkey.
If it is assigned, you need to disable the assignment in sven's configuration
before re-assigning it.
.IP "\(bu" 3
Right-click the keyboard icon -- located in the desktop panel icon tray --to
open sven's menu, and select Preferences
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 3
Click Keyboard > New > Description and type \fIStand-alone System Menu Win+s\fR
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 3
Click inside input field Key Code with your mouse, then press keys \(dqWindows\(dq
and \(dqs\(dq together, don't press other keys
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 3
Click inside input field Text Display with your mouse, then type \(dqSystem and
Applications\(dq
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 3
Click the Program radio button, and type: «\fCgmenu2\fR»
.if n \
.sp -1
.if t \
.sp -0.25v
.IP "\(bu" 3
Click OK and close sven.
.LP
Press Win+s to test the global hotkey.
.SS
Setting a theme (optional)
.LP
If «\fCquicklaunch\fR»\fB:5\fR» is installed, you can theme the gmenu2 menu using
the themes and instructions provided with the quicklaunch package.
.SS
Help
.LP
This file is \(dqthe\(dq help file, so keep it around for future reference
because it isn't installed by default.  However, if the «\fCman\fR» command is
installed, you will be able to view these contents by running command:
.LP
.nf
.ft CR
man gmenu2
.ft
.fi
.PP
Tip: by default the menu contents are cached. To troubleshoot any issues start
by removing the menu cache directory, «\fC/tmp/gmenu_$USER\fR», where «\fC$USER\fR» is your
login name.
.SS
AUTHOR
.LP
step
.PP
.SS
LINKS
.LP
\fBHomepage\fR
\fIhttps://github.com/step-/scripts-to-go#gmenu2\fR
.PP
\fB:1\fR release page
\fIhttps://github.com/step-/scripts-to-go/releases\fR
.PP
\fB:2\fR gtkmenuplus
\fIhttps://github.com/step-/gtkmenuplus\fR
.IP "\(bu" 3
formatting directives ( «\fCman 5 gtkmenuplus\fR» )
\fIhttps://github.com/step-/gtkmenuplus/blob/master/docs/menu_configuration_file_format.md\fR
.LP
\fB:3\fR sven multimedia keyboard manager
.IP "\(bu" 3
source
\fIhttp://distro.ibiblio.org/fatdog/source/900/sven-2023.07.02.tar.bz2\fR
.IP "\(bu" 3
64-bit binary
\fIhttp://distro.ibiblio.org/fatdog/packages/900/sven-2023.07-x86_64-1.txz\fR
.LP
\fB:4\fR Fatdog64 Linux
\fIhttp://distro.ibiblio.org/fatdog/web/\fR
.PP
\fB:5\fR Quicklaunch user menu
\fIhttps://github.com/step-/scripts-to-go/#quicklaunch\fR
.PP
\fB:6\fR Gmenu2 extension: Fatdog64 Control Panel
\fIhttps://github.com/step-/scripts-to-go/#gmenu2-fdcp\fR
